import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Daily Grind",
  description: "Generated by Song",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
