import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/page";

const montserrat = Montserrat({
  subsets:['latin'],
  weight: ['100','300','700' ],
})
export const metadata = {
  title: "Studio Terra ",
  description: "Generated by Song",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
